version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - winter-camp-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/techtutor
      - SESSION_SECRET=winter-camp-secret-key-change-in-production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=production
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - winter-camp-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=techtutor
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - winter-camp-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - winter-camp-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  winter-camp-network:
    driver: bridge
